### ISSUE TITLE
uparser moved to scope NPM package (`@webreflection/*`)

### ISSUE THREAD

**Issue by danielweck** [WebReflection/uhtml-ssr#5]
Discrepancy between `uhtml-ssr` and `uhtml`:

https://github.com/WebReflection/uhtml-ssr/blob/5c7c7340d028f9c8aea1a915d3855b16b78565a8/package.json#L60
(`v0.2.1` from 2 years ago https://www.npmjs.com/package/uparser )

==>

https://github.com/WebReflection/uhtml/blob/521a43e3a907ef30e0aaefcdb101746760c793cb/package.json#L39
```
"@webreflection/uparser": "^0.2.4",
```
(`v0.2.4` from 3 days ago https://www.npmjs.com/package/@webreflection/uparser )

**Comment by WebReflection** [comment]
new *uparser* means a major, as it might break some edge case/corner I haven't tested within my projects ... this is why I was waiting for *uhtml* bugs to happen (as [it did already](https://github.com/WebReflection/uhtml/issues/64)) before moving to the new module ... the new module might also become again the old one, as I use the namespace pretty often just to test new ideas, before landing these "*officially*".

Anyway, will keep this open, but because there's no hydration between the two, the *uparser* makes concretely zero difference in practice.
